### ISSUE TITLE
rotation script

### ISSUE THREAD

**Issue by pawarpooja** [gregwchase/dsi-capstone#1]
Hello gregwchase,  can you please tell me which data is stored in trainLabels_master.csv?

**Comment by gregwchase** [comment]
@pawarpooja trainLabels_master.csv is the first set of labels. I have another CSV file in the repo I used after dropping certain images, due to them being pitch black/ unsuitable for training the CNN.

**Comment by pawarpooja** [comment]
Okay thank you @gregwchase
