### ISSUE TITLE
GPU problem

### ISSUE THREAD

**Issue by shivamjoshi26** [gregwchase/dsi-capstone#12]
ValueError: To call `multi_gpu_model` with `gpus=8`, we expect the following devices to be available: ['/cpu:0', '/gpu:0', '/gpu:1', '/gpu:2', '/gpu:3', '/gpu:4', '/gpu:5', '/gpu:6', '/gpu:7']. However this machine only has: ['/cpu:0', '/xla_cpu:0', '/xla_gpu:0', '/gpu:0']. Try reducing `gpus`

**Comment by Kigeek-02** [comment]
Hi Shivam,
The ValueError is because you don’t have 8-GPUs to run the model.  However, if you are on Colab – you need to setup the TPU first which requires additional line of coding to get access to the 8 Gpus.

Kind Regards

Kiran

________________________________

**Comment by SaurabhTiwari1999** [comment]
CAN YOU TELL WHICH CODE?
