### ISSUE TITLE
`X_train_256_v2.npy` saved?

### ISSUE THREAD

**Issue by ghost** [gregwchase/dsi-capstone#6]
In `image_to_array.py` I see you saved`X_train.npy`, but I don't see where you saved `X_train_256_v2.npy` even though you end up loading it as the training data in all of your CNN models.  Is the code to save `X_train_256_v2.npy` missing?  

I feel like you meant to save `X_train.npy` as `X_train_256_v2.npy` since you ended up using the labels from `trainLabels_master_256_v2.csv` when you called `convert_images_to_arrays_train`, but I am not sure.

**Comment by gregwchase** [comment]
@klawal Yes, I meant to save it as `X_train.npy`; I've got multiple versions of the processed files. This will be changed in the next iteration to reflect that.
