### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '../data/train-resized-256/19_left.jpeg'

### ISSUE THREAD

**Issue by ghost** [gregwchase/dsi-capstone#8]
Hi I am running the !python preprocess_images.py 
I used training.zip.001 and test.zip.001  only as per the script "resize_images.py"
Should i have to process / rotate all the train and test images before running the pre-process ?
TRACE of running preprocess_images.py

Started Image preprocess
Traceback (most recent call last):
  File "preprocess_images.py", line 31, in <module>
    trainLabels['black'] = find_black_images('../data/train-resized-256/', trainLabels)
  File "preprocess_images.py", line 21, in find_black_images
    return [1 if np.mean(np.array(Image.open(file_path + img))) == 0 else 0 for img in lst_imgs]
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2312, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '../data/train-resized-256/19_left.jpeg'
Sat Oct 20 08:42:36 UTC 2018
Ended Image preprocess

**Comment by davidzeno** [comment]
The command `7za x train.zip.001` from script "resize_images.py" actually extracts all the files from train.zip.001  train.zip.002  train.zip.003  train.zip.004  train.zip.005, not just from train.zip.001.

Per error: Image 19_left.jpeg is missing.
You need to download and decompress all the data. (83G compressed and 95G decompressed) and after that you will be able to locate image 19_left.jpeg.
